version: '3.8'

services:
  customer-api:
    image: 'customer-api'
    build:
      context: .
    container_name: customer-api
    expose:
      - 8081
    ports:
      - 8081:8081
    links:
      - postgres  
    # networks:
    #    - customer-postgres   
    # depends_on:
    #   - postgres
    # environment:
    #   - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/start_data_engineer
    #   - SPRING_DATASOURCE_USERNAME=start_data_engineer
    #   - SPRING_DATASOURCE_PASSWORD=password
    #   - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  # postgres:
  #   image: 'debezium/postgres:12'
  #   container_name: postgres
  #   expose:
  #     - 5432
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - customer-postgres  
  #   environment:
  #     - POSTGRES_USER=start_data_engineer
  #     - POSTGRES_PASSWORD=password

# networks:
#   customer-postgres:
      
      
      