openapi: '3.0.2'

info:
  title: Customer API
  version: '1.0'
  contact:
    name: Accenture
    email: contact@example.com
    url: https://example.com/

tags:
  - name: Customer API
    description: Customer Service related operations
    
paths:
  /customer:
    post:
      description: Create Customer
      summary: Create Customer
      tags: [ 'Customer API' ]
      operationId: createCustomer
      requestBody:
        description: "Create Customer"
        content:
         application/json:
          schema:
            $ref: '#/components/schemas/Customer'   
      responses:
        '200':
          description: Customer Create Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    put:
      operationId: updateCustomer
      description: Update Customer
      summary: Update Customer
      tags: [ 'Customer API' ]
      
      requestBody:
        description: "Update Customer"
        content:
         application/json:
          schema:
            $ref: '#/components/schemas/Customer'   
      responses:
        '200':
          description: Customer Create Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'       

  /customer/{id}:
    delete:
      operationId: deleteCustomer
      parameters:
        - name: id
          in: path
          description: delete customer
          required: true
          schema: 
            type: string
          
      summary: Delete Customer
      tags: [ 'Customer API' ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Customer Deleted Successfully          
                
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
            
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '400':
          description: Invalid Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'      
    get:
      operationId: getCustomer
      parameters:
        - name: id
          in: path
          description: find customer
          required: true
          schema: 
            type: string
          
      summary: Get customer details
      tags: [ 'Customer API' ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
            
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '400':
          description: Invalid Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'      
          
components:
  schemas:
    Customer:
      description: This is a customer model
      type: object
      required:
        - "customerId"
      properties:
        customerId:
          type: string
          description: "Id of the customer"
          example: 12345
          minLength: 5
          maxLength: 8
        customerName:
          type: string
          description: Name of the customer
          example: Jessica Alba
        customerAddress:
          type: string
          description: Customer address
          example: 900 Main Street, 55

    InternalServerError:
        description: Internal Server Error
        properties:
          error:
            type: integer
            example: 500
          message:
            type: string
            example: Internal Server Error  
    NotFoundError:
        description: Internal Server Error
        properties:
          error:
            type: integer
            example: 404
          message:
            type: string
            example: Customer Not Found
    BadRequestError:
        description: Internal Server Error
        properties:
          error:
            type: integer
            example: 400
          message:
            type: string
            example: Invalid customer id                
            

